# Generated by Django 4.1.7 on 2023-03-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
                ('dept_location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_age', models.IntegerField()),
                ('start_date', models.DateField()),
                ('emp_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('TE', 'Temp Emp')], max_length=2)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.department')),
            ],
        ),
    ]
